import { Outfit, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Novabooks",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"  suppressHydrationWarning
      className={` ${outfit.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <body className="bg-slate-50 text-slate-900 selection:bg-nova-gold/30">
        {children}
      </body>
    </html>
  );
}
